name: lyrics
channels:
- soumith
- defaults
dependencies:
- _nb_ext_conf=0.4.0=py36_1
- alabaster=0.7.10=py36h306e16b_0
- anaconda-client=1.6.5=py36h19c0dcd_0
- asn1crypto=0.22.0=py36h265ca7c_1
- babel=2.5.0=py36h7d14adf_0
- bleach=2.0.0=py36h688b259_0
- boto=2.48.0=py36h6e4cd66_1
- bz2file=0.98=py36_0
- ca-certificates=2017.08.26=h1d4fec5_0
- certifi=2017.7.27.1=py36h8b7b77e_0
- cffi=1.10.0=py36had8d393_1
- chardet=3.0.4=py36h0f667ec_1
- clyent=1.2.2=py36h7e57e65_1
- cryptography=2.0.3=py36ha225213_1
- cycler=0.10.0=py36h93f1223_0
- dbus=1.10.22=h3b5a359_0
- decorator=4.1.2=py36hd076ac8_0
- docutils=0.14=py36hb0f60f5_0
- entrypoints=0.2.3=py36h1aec115_2
- expat=2.2.4=hc00ebd1_1
- fontconfig=2.12.4=h88586e7_1
- freetype=2.8=h52ed37b_0
- gensim=3.0.1=py36h4ebfbf4_0
- glib=2.53.6=hc861d11_1
- gmp=6.1.2=hb3b607b_0
- gst-plugins-base=1.12.2=he3457e5_0
- gstreamer=1.12.2=h4f93127_0
- html5lib=0.999999999=py36h2cfc398_0
- icu=58.2=h211956c_0
- idna=2.6=py36h82fb2a8_1
- imagesize=0.7.1=py36h52d8127_0
- intel-openmp=2018.0.0=h15fc484_7
- ipykernel=4.6.1=py36hbf841aa_0
- ipython=6.1.0=py36hc72a948_1
- ipython_genutils=0.2.0=py36hb52b0d5_0
- ipywidgets=7.0.0=py36h7b55c3a_0
- jedi=0.10.2=py36h552def0_0
- jinja2=2.9.6=py36h489bce4_1
- jpeg=9b=habf39ab_1
- jsonschema=2.6.0=py36h006f8b5_0
- jupyter=1.0.0=py36h9896ce5_0
- jupyter_client=5.1.0=py36h614e9ea_0
- jupyter_console=5.2.0=py36he59e554_1
- jupyter_core=4.3.0=py36h357a921_0
- libedit=3.1=heed3624_0
- libffi=3.2.1=h4deb6c0_3
- libgcc=7.2.0=h69d50b8_2
- libgcc-ng=7.2.0=h7cc24e2_2
- libgfortran-ng=7.2.0=h9f7466a_2
- libpng=1.6.32=hda9c8bc_2
- libsodium=1.0.13=h31c71d8_2
- libstdcxx-ng=7.2.0=h7a57d05_2
- libtiff=4.0.8=h90200ff_9
- libxcb=1.12=h84ff03f_3
- libxml2=2.9.4=h6b072ca_5
- markupsafe=1.0=py36hd9260cd_1
- matplotlib=2.1.0=py36hba5de38_0
- mistune=0.7.4=py36hbab8784_0
- mkl=2018.0.0=hb491cac_4
- nb_anacondacloud=1.4.0=py36_0
- nb_conda=2.2.1=py36h8118bb2_0
- nb_conda_kernels=2.1.0=py36_0
- nbconvert=5.3.1=py36hb41ffb7_0
- nbformat=4.4.0=py36h31c9010_0
- nbpresent=3.0.2=py36h5f95a39_1
- ncurses=6.0=h06874d7_1
- nltk=3.2.4=py36h1a0979f_0
- notebook=5.0.0=py36h0b20546_2
- numpy=1.13.3=py36ha12f23b_0
- olefile=0.44=py36h79f9f78_0
- openssl=1.0.2l=h077ae2c_5
- pandoc=1.19.2.1=hea2e7c5_1
- pandocfilters=1.4.2=py36ha6701b7_1
- pcre=8.41=hc71a17e_0
- pexpect=4.2.1=py36h3b9d41b_0
- pickleshare=0.7.4=py36h63277f8_0
- pillow=4.2.1=py36h9119f52_0
- pip=9.0.1=py36h6c6f9ce_4
- prompt_toolkit=1.0.15=py36h17d85b1_0
- ptyprocess=0.5.2=py36h69acd42_0
- pycparser=2.18=py36hf9f622e_1
- pygments=2.2.0=py36h0d3125c_0
- pyopenssl=17.2.0=py36h5cc804b_0
- pyparsing=2.2.0=py36hee85983_1
- pyqt=5.6.0=py36h0386399_5
- pysocks=1.6.7=py36hd97a5b1_1
- python=3.6.3=hefd0734_2
- python-dateutil=2.6.1=py36h88d3b88_1
- pytz=2017.2=py36hc2ccc2a_1
- pyyaml=3.12=py36hafb9ca4_1
- pyzmq=16.0.2=py36h3b0cf96_2
- qt=5.6.2=h974d657_12
- qtconsole=4.3.1=py36h8f73b5b_0
- readline=7.0=hac23ff0_3
- requests=2.18.4=py36he2e5f8d_1
- scikit-learn=0.19.1=py36h7aa7ec6_0
- scipy=0.19.1=py36h9976243_3
- setuptools=36.5.0=py36he42e2e1_0
- simplegeneric=0.8.1=py36h2cb9092_0
- sip=4.18.1=py36h51ed4ed_2
- six=1.11.0=py36h372c433_1
- smart_open=1.5.3=py36_0
- snowballstemmer=1.2.1=py36h6febd40_0
- sphinx=1.6.3=py36he5f0bdb_0
- sphinxcontrib=1.0=py36h6d0f590_1
- sphinxcontrib-websupport=1.0.1=py36hb5cb234_1
- sqlite=3.20.1=h6d8b0f3_1
- terminado=0.6=py36ha25a19f_0
- testpath=0.3.1=py36h8cadb63_0
- tk=8.6.7=h5979e9b_1
- tornado=4.5.2=py36h1283b2a_0
- traitlets=4.3.2=py36h674d592_0
- typing=3.6.2=py36h7da032a_0
- urllib3=1.22=py36hbe7ace6_0
- wcwidth=0.1.7=py36hdf4376a_0
- webencodings=0.5.1=py36h800622e_1
- wheel=0.29.0=py36he7f4e38_1
- widgetsnbextension=3.0.2=py36hd01bb71_1
- xz=5.2.3=h2bcbf08_1
- yaml=0.1.7=h96e3832_1
- zeromq=4.2.2=hb0b69da_1
- zlib=1.2.11=hfbfcf68_1
- pytorch=0.2.0=py36hf0d2509_4cu75
- torchvision=0.1.9=py36h7584368_1
- pip:
  - hanziconv==0.3.2
  - ipython-genutils==0.2.0
  - jupyter-client==5.1.0
  - jupyter-console==5.2.0
  - jupyter-core==4.3.0
  - nb-anacondacloud==1.4.0
  - nb-conda==2.2.1
  - nb-conda-kernels==2.1.0
  - prompt-toolkit==1.0.15
  - pypinyin==0.27.0
  - smart-open==1.5.3
  - sphinx-rtd-theme==0.2.4
  - thulac==0.1.2
  - torch==0.2.0.post4

